### ISSUE TITLE
Sharing incorrect links crashes Unalix

### ISSUE THREAD

**Issue by k3n01** [AmanoTeam/UnalixAndroid#6]
Links such as:
`Demo text, https://example.org`

No one would want to use it on a bogus link, but the app should never crash either.

**Comment by alissonlauffer** [comment]
I couldn't reproduce the crash here with the provided link, but when using malformed links like `https:example.org`, `https:/example.org` and `https:\\example.org`, it causes a crash.

**Comment by SnwMds** [comment]
> I couldn't reproduce the crash here with the provided link

I think in this specific case he was trying to share a text containing a URL.

Here is how I managed to reproduce it:

```
am start \
    -a android.intent.action.SEND \
    -t text/plain \
    -e 'android.intent.extra.TEXT' 'Demo text, https://example.org https://example.org'
```

Crash log:

```
F libc    : /buildbot/src/android/ndk-r24-release/toolchain/llvm-project/libcxx/../../../toolchain/llvm-project/libcxxabi/src/abort_message.cpp:72: abort_message: assertion "terminating with uncaught exception of type std::invalid_argument: stoi: no conversion" failed
F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 9021 (ServiceStartArg), pid 9006 (x:unalixprocess)
```
